## Introduction to Numpy

In [3]:
import numpy as np
print("numpy version:", np.__version__)

numpy version: 1.19.2


In [21]:
# data structure in Numpy -> array n-dimensional: ndarray
arr_int = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_int, "type:", type(arr_int), "shape:", arr_int.shape)
# shape -> bentuk
print("axis 0:", arr_int.shape[0], "axis 1:", arr_int.shape[1])
#axis 0: 1 dimension, axis 1: 2 dimension, axis-n: n-dimension
print("length:", len(arr_int))

# example 1 dimension
arr1d_float = np.array([.1, .2, .3, .4])
print(arr1d_float, "type:", type(arr1d_float), "shape:", arr1d_float.shape)
print("axis 0:", arr1d_float.shape[0])
print("length:", len(arr1d_float))

# example 3 dimensio
arr3d_int = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3d_int, "type:", type(arr3d_int), "shape:", arr3d_int.shape)
print(
    "axis 0:", arr3d_int.shape[0],
    "axis 1:", arr3d_int.shape[1],
    "axis 2:", arr3d_int.shape[2]
)
print("length:", len(arr3d_int))

[[1 2 3]
 [4 5 6]] type: <class 'numpy.ndarray'> shape: (2, 3)
axis 0: 2 axis 1: 3
length: 2
[0.1 0.2 0.3 0.4] type: <class 'numpy.ndarray'> shape: (4,)
axis 0: 4
length: 4
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] type: <class 'numpy.ndarray'> shape: (2, 2, 2)
axis 0: 2 axis 1: 2 axis 2: 2
length: 2


In [19]:
# compare with list
print([1, 2, 3], [4, 5, 6])

[1, 2, 3] [4, 5, 6]


In [45]:
arr_zeros = np.zeros((2, 3))
print(arr_zeros, arr_zeros.dtype, type(arr_zeros), arr_zeros.shape)

arr_ones = np.ones((2, 4))
print(arr_ones, arr_ones.dtype, type(arr_ones), arr_ones.shape)

arr_arange = np.arange(1, 2, .1)
print(arr_arange, arr_arange.dtype, type(arr_arange), arr_arange.shape)

arr_empty = np.empty((100, 100))
print(arr_empty, arr_empty.dtype, type(arr_empty), arr_empty.shape)

[[0. 0. 0.]
 [0. 0. 0.]] float64 <class 'numpy.ndarray'> (2, 3)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64 <class 'numpy.ndarray'> (2, 4)
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9] float64 <class 'numpy.ndarray'> (10,)
[[1.04037074e-311 1.04036628e-311 2.12199579e-314 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 ...
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]] float64 <class 'numpy.ndarray'> (100, 100)


In [40]:
dummy_list = [[1, 2, 3], [4, 5, 6]]
print("list:", dummy_list)
print("array:", arr_int)

# indexing
print(dummy_list[0][0], dummy_list[0][:2])
print(arr_int[0, 0], arr_int[0, :2])
print(arr_int[::-1, ::-1])

list: [[1, 2, 3], [4, 5, 6]]
array: [[1 2 3]
 [4 5 6]]
1 [1, 2]
1 [1 2]
[[6 5 4]
 [3 2 1]]


In [42]:
# ndim and size of ndarray
print("num of dimension:", arr_int.ndim)
print("num of dimension:", arr3d_int.ndim)

print("total_items:", arr_int.size)
print("total items:", arr3d_int.size)

num of dimension: 2
num of dimension: 3
total_items: 6
total items: 8


In [43]:
# flatten
print("before flatten:", arr_int)
print("after flatten:", arr_int.flatten())

before flatten: [[1 2 3]
 [4 5 6]]
after flatten: [1 2 3 4 5 6]


In [57]:
# append
print(np.append(arr1d_float, [10, 11, 12])) # append array with defined array
print(np.append(arr_int, [[10, 11, 12]], axis=0))
print(np.append(arr_int, [[10], [11]], axis=1))
print(np.append(arr_int, arr_int, axis=1)) # append with existing arrays, only 2
print(np.concatenate([arr_int, arr_int, arr_int]))  # append with existing arrays, > 2
print(np.concatenate([arr_int, arr_zeros], axis=0))
print(np.concatenate([arr_int] * 5, axis=1)) # append with existing arrays, multiplied

[ 0.1  0.2  0.3  0.4 10.  11.  12. ]
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]


In [59]:
# delete
print(arr3d_int)
print(np.delete(arr3d_int, 1, axis=0))
print(np.delete(arr3d_int, -1, axis=1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [3 4]]]
[[[1 2]]

 [[5 6]]]


In [75]:
# reshape -> new shape hrs kompatible dgn array original
print(arr3d_int, arr3d_int.shape)
print(arr3d_int.flatten())
print(np.reshape(arr3d_int, (2, 4)), np.reshape(arr3d_int, (2, 4)).ndim)
print(arr3d_int.reshape(2, 4))

# resize -> tdk harus kompatibel
print(np.resize(arr3d_int, (5, 3)).ndim)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]] 2
[[1 2 3 4]
 [5 6 7 8]]
2


In [85]:
# newaxis -> npnewaxis akan nambah 1 dimensi
print(arr1d_float.shape)
print(arr1d_float[np.newaxis],)

arr2d_float = arr1d_float[np.newaxis]
print(arr2d_float, arr2d_float.shape)

print(arr1d_float[None]) # cara lain selain npnewaxis

print(arr3d_int[:, :, :, np.newaxis].shape) # jmlh ":" sesuai dimensi, atau
print(arr3d_int[..., np.newaxis].shape) # "..." -> elipsis, utk kalo nggatau dimensinya ada brp
print(arr3d_int[:, np.newaxis, ...].shape)

(4,)
[[0.1 0.2 0.3 0.4]]
[[0.1 0.2 0.3 0.4]] (1, 4)
[[0.1 0.2 0.3 0.4]]
(2, 2, 2, 1)
(2, 2, 2, 1)
(2, 1, 2, 2)


In [92]:
# transpose
print(arr_int)
print(arr_int.T)
print(np.transpose(arr_int))
print(arr_int.reshape(arr_int.shape[1], arr_int.shape[0]))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2]
 [3 4]
 [5 6]]


In [108]:
# mathematical operation
print(dummy_list + dummy_list)
print(arr_int + arr_int) # harus sama axisnya
print(arr3d_int * 8)
print(arr1d_float * arr1d_float)
print(arr_int * arr_int)
print(arr_int / arr_int)

print(np.round(arr1d_float ** arr1d_float, decimals=3))

print(arr_int)
print(arr_int.sum(axis=0))
print(arr_int.sum(axis=1, keepdims=True))

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[[ 8 16]
  [24 32]]

 [[40 48]
  [56 64]]]
[0.01 0.04 0.09 0.16]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0.794 0.725 0.697 0.693]
[[1 2 3]
 [4 5 6]]
[5 7 9]
[[ 6]
 [15]]


In [113]:
# np.dot
print(arr1d_float)
print(np.dot(arr1d_float, arr1d_float))

print(arr3d_int)
print(np.dot(arr3d_int, 10))

print(arr_int)
print(np.dot(arr_int, arr_int.T))

[0.1 0.2 0.3 0.4]
0.3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
[[1 2 3]
 [4 5 6]]
[[14 32]
 [32 77]]


In [126]:
# matrix multiplication
print(arr_int)
print(np.matmul(arr_int.T, arr_int))
print(np.matmul(arr_int, arr_int.T))



[[1 2 3]
 [4 5 6]]
[[17 22 27]
 [22 29 36]
 [27 36 45]]
[[14 32]
 [32 77]]
[[ 1  4  9]
 [16 25 36]]


In [133]:
# random
np.random.seed(10)
print(np.random.randint(10, size=(7, 5)))
print(np.random.uniform(10, size=(7, 5)))
print(np.random.randn(12, 100))
print(np.random.normal(1., 10, size=(5, 1)))

[[9 4 0 1 9]
 [0 1 8 9 0]
 [8 6 4 3 0]
 [4 6 8 1 8]
 [4 1 3 6 5]
 [3 9 6 9 1]
 [9 4 2 6 7]]
[[9.89390774 4.49250993 7.0130597  4.96316471 6.98050318]
 [6.29935709 9.30830048 2.32261309 6.0401129  8.90241268]
 [3.41438838 8.75095781 3.09807956 2.51209209 7.2119975 ]
 [4.62175939 2.14846786 1.1528122  5.79337049 2.11829955]
 [7.33538171 8.81838052 2.4146386  4.06867326 4.64104356]
 [6.07281672 6.79374706 4.71582167 8.65475797 8.45885262]
 [6.42551929 4.25843592 6.64732043 9.97833915 5.0606528 ]]
[[ 0.71588314 -1.18576855 -0.6363279  ...  1.46127126 -0.14540648
   0.73097974]
 [-0.61770627  1.68435892 -0.87947247 ...  1.84132241 -1.80952525
  -0.50499114]
 [ 1.60266609  1.18937788  0.25529429 ...  0.65194319 -0.12614606
   0.10251265]
 ...
 [-0.31602245 -2.30673157 -0.98906551 ... -0.74562225  0.38911965
  -1.7026256 ]
 [-0.20523372  0.46628462  0.44095853 ... -1.45702894 -0.9324995
  -0.80880996]
 [ 0.03825287  0.29182488  0.22341588 ... -0.62883318  1.83318832
   0.10892427]]
[[ 0.17167

In [ ]:
# 